name: sandbox-devel
channels:
  - conda-forge
dependencies:
  - codecov
  - dask
  - netcdf4
  - pip
  - pytest
  - pytest-cov
  - xarray
  - numpydoc
  - nbsphinx
  - pre-commit
  - numpy_groupies
  - pooch
  - toolz
  - pip:
    - icecream
